namespace Ucpf.Core.Model.Visitors {
	public interface IUnifiedModelVisitor {
		void Visit(UnifiedBinaryOperator element);
		void Visit(UnifiedUnaryOperator element);
		void Visit(UnifiedArgument element);
		void Visit(UnifiedArgumentCollection element);
		void Visit(UnifiedBinaryExpression element);
		void Visit(UnifiedBlock element);
		void Visit(UnifiedCall element);
		void Visit(UnifiedFunctionDefinition element);
		void Visit(UnifiedIf element);
		void Visit(UnifiedParameter element);
		void Visit(UnifiedParameterCollection element);
		void Visit(UnifiedIdentifier element);
		void Visit(UnifiedModifier element);
		void Visit(UnifiedModifierCollection element);
		void Visit(UnifiedImport element);
		void Visit(UnifiedConstructorDefinition element);
		void Visit(UnifiedProgram element);
		void Visit(UnifiedClassDefinition element);
		void Visit(UnifiedVariableDefinition element);
		void Visit(UnifiedNew element);
		void Visit(UnifiedFor element);
		void Visit(UnifiedForeach element);
		void Visit(UnifiedUnaryExpression element);
		void Visit(UnifiedProperty element);
		void Visit(UnifiedType element);
		void Visit(UnifiedExpressionCollection element);
		void Visit(UnifiedWhile element);
		void Visit(UnifiedDoWhile element);
		void Visit(UnifiedIndexer element);
		void Visit(UnifiedTypeArgument element);
		void Visit(UnifiedTypeArgumentCollection element);
		void Visit(UnifiedSwitch element);
		void Visit(UnifiedCaseCollection element);
		void Visit(UnifiedCase element);
		void Visit(UnifiedSpecialExpression element);
		void Visit(UnifiedSpecialBlock element);
		void Visit(UnifiedCatch element);
		void Visit(UnifiedTypeCollection element);
		void Visit(UnifiedCatchCollection element);
		void Visit(UnifiedTry element);
		void Visit(UnifiedCast element);
		void Visit(UnifiedTypeParameterCollection element);
		void Visit(UnifiedTypeConstrain element);
		void Visit(UnifiedTypeConstrainCollection element);
		void Visit(UnifiedTypeParameter element);
		void Visit(UnifiedTypeSupplement element);
		void Visit(UnifiedTypeSupplementCollection element);
		void Visit(UnifiedTernaryOperator element);
		void Visit(UnifiedTernaryExpression element);
		void Visit(UnifiedVariableDefinitionBody element);
		void Visit(UnifiedVariableDefinitionBodyCollection element);
		void Visit(UnifiedIdentifierCollection element);
		void Visit(UnifiedQualifiedIdentifier element);
		void Visit(UnifiedLabel element);
		void Visit(UnifiedExpressionList element);
		void Visit(UnifiedBooleanLiteral element);
		void Visit(UnifiedFractionLiteral element);
		void Visit(UnifiedIntegerLiteral element);
		void Visit(UnifiedStringLiteral element);
		void Visit(UnifiedNullLiteral element);
	}

	public interface IUnifiedModelVisitor<in TData> {
		void Visit(UnifiedBinaryOperator element, TData data);
		void Visit(UnifiedUnaryOperator element, TData data);
		void Visit(UnifiedArgument element, TData data);
		void Visit(UnifiedArgumentCollection element, TData data);
		void Visit(UnifiedBinaryExpression element, TData data);
		void Visit(UnifiedBlock element, TData data);
		void Visit(UnifiedCall element, TData data);
		void Visit(UnifiedFunctionDefinition element, TData data);
		void Visit(UnifiedIf element, TData data);
		void Visit(UnifiedParameter element, TData data);
		void Visit(UnifiedParameterCollection element, TData data);
		void Visit(UnifiedIdentifier element, TData data);
		void Visit(UnifiedModifier element, TData data);
		void Visit(UnifiedModifierCollection element, TData data);
		void Visit(UnifiedImport element, TData data);
		void Visit(UnifiedConstructorDefinition element, TData data);
		void Visit(UnifiedProgram element, TData data);
		void Visit(UnifiedClassDefinition element, TData data);
		void Visit(UnifiedVariableDefinition element, TData data);
		void Visit(UnifiedNew element, TData data);
		void Visit(UnifiedFor element, TData data);
		void Visit(UnifiedForeach element, TData data);
		void Visit(UnifiedUnaryExpression element, TData data);
		void Visit(UnifiedProperty element, TData data);
		void Visit(UnifiedType element, TData data);
		void Visit(UnifiedExpressionCollection element, TData data);
		void Visit(UnifiedWhile element, TData data);
		void Visit(UnifiedDoWhile element, TData data);
		void Visit(UnifiedIndexer element, TData data);
		void Visit(UnifiedTypeArgument element, TData data);
		void Visit(UnifiedTypeArgumentCollection element, TData data);
		void Visit(UnifiedSwitch element, TData data);
		void Visit(UnifiedCaseCollection element, TData data);
		void Visit(UnifiedCase element, TData data);
		void Visit(UnifiedSpecialExpression element, TData data);
		void Visit(UnifiedSpecialBlock element, TData data);
		void Visit(UnifiedCatch element, TData data);
		void Visit(UnifiedTypeCollection element, TData data);
		void Visit(UnifiedCatchCollection element, TData data);
		void Visit(UnifiedTry element, TData data);
		void Visit(UnifiedCast element, TData data);
		void Visit(UnifiedTypeParameterCollection element, TData data);
		void Visit(UnifiedTypeConstrain element, TData data);
		void Visit(UnifiedTypeConstrainCollection element, TData data);
		void Visit(UnifiedTypeParameter element, TData data);
		void Visit(UnifiedTypeSupplement element, TData data);
		void Visit(UnifiedTypeSupplementCollection element, TData data);
		void Visit(UnifiedTernaryOperator element, TData data);
		void Visit(UnifiedTernaryExpression element, TData data);
		void Visit(UnifiedVariableDefinitionBody element, TData data);
		void Visit(UnifiedVariableDefinitionBodyCollection element, TData data);
		void Visit(UnifiedIdentifierCollection element, TData data);
		void Visit(UnifiedQualifiedIdentifier element, TData data);
		void Visit(UnifiedLabel element, TData data);
		void Visit(UnifiedExpressionList element, TData data);
		void Visit(UnifiedBooleanLiteral element, TData data);
		void Visit(UnifiedFractionLiteral element, TData data);
		void Visit(UnifiedIntegerLiteral element, TData data);
		void Visit(UnifiedStringLiteral element, TData data);
		void Visit(UnifiedNullLiteral element, TData data);
	}

	public interface IUnifiedModelVisitor<in TData, out TResult> {
		TResult Visit(UnifiedBinaryOperator element, TData data);
		TResult Visit(UnifiedUnaryOperator element, TData data);
		TResult Visit(UnifiedArgument element, TData data);
		TResult Visit(UnifiedArgumentCollection element, TData data);
		TResult Visit(UnifiedBinaryExpression element, TData data);
		TResult Visit(UnifiedBlock element, TData data);
		TResult Visit(UnifiedCall element, TData data);
		TResult Visit(UnifiedFunctionDefinition element, TData data);
		TResult Visit(UnifiedIf element, TData data);
		TResult Visit(UnifiedParameter element, TData data);
		TResult Visit(UnifiedParameterCollection element, TData data);
		TResult Visit(UnifiedIdentifier element, TData data);
		TResult Visit(UnifiedModifier element, TData data);
		TResult Visit(UnifiedModifierCollection element, TData data);
		TResult Visit(UnifiedImport element, TData data);
		TResult Visit(UnifiedConstructorDefinition element, TData data);
		TResult Visit(UnifiedProgram element, TData data);
		TResult Visit(UnifiedClassDefinition element, TData data);
		TResult Visit(UnifiedVariableDefinition element, TData data);
		TResult Visit(UnifiedNew element, TData data);
		TResult Visit(UnifiedFor element, TData data);
		TResult Visit(UnifiedForeach element, TData data);
		TResult Visit(UnifiedUnaryExpression element, TData data);
		TResult Visit(UnifiedProperty element, TData data);
		TResult Visit(UnifiedType element, TData data);
		TResult Visit(UnifiedExpressionCollection element, TData data);
		TResult Visit(UnifiedWhile element, TData data);
		TResult Visit(UnifiedDoWhile element, TData data);
		TResult Visit(UnifiedIndexer element, TData data);
		TResult Visit(UnifiedTypeArgument element, TData data);
		TResult Visit(UnifiedTypeArgumentCollection element, TData data);
		TResult Visit(UnifiedSwitch element, TData data);
		TResult Visit(UnifiedCaseCollection element, TData data);
		TResult Visit(UnifiedCase element, TData data);
		TResult Visit(UnifiedSpecialExpression element, TData data);
		TResult Visit(UnifiedSpecialBlock element, TData data);
		TResult Visit(UnifiedCatch element, TData data);
		TResult Visit(UnifiedTypeCollection element, TData data);
		TResult Visit(UnifiedCatchCollection element, TData data);
		TResult Visit(UnifiedTry element, TData data);
		TResult Visit(UnifiedCast element, TData data);
		TResult Visit(UnifiedTypeParameterCollection element, TData data);
		TResult Visit(UnifiedTypeConstrain element, TData data);
		TResult Visit(UnifiedTypeConstrainCollection element, TData data);
		TResult Visit(UnifiedTypeParameter element, TData data);
		TResult Visit(UnifiedTypeSupplement element, TData data);
		TResult Visit(UnifiedTypeSupplementCollection element, TData data);
		TResult Visit(UnifiedTernaryOperator element, TData data);
		TResult Visit(UnifiedTernaryExpression element, TData data);
		TResult Visit(UnifiedVariableDefinitionBody element, TData data);
		TResult Visit(UnifiedVariableDefinitionBodyCollection element, TData data);
		TResult Visit(UnifiedIdentifierCollection element, TData data);
		TResult Visit(UnifiedQualifiedIdentifier element, TData data);
		TResult Visit(UnifiedLabel element, TData data);
		TResult Visit(UnifiedExpressionList element, TData data);
		TResult Visit(UnifiedBooleanLiteral element, TData data);
		TResult Visit(UnifiedFractionLiteral element, TData data);
		TResult Visit(UnifiedIntegerLiteral element, TData data);
		TResult Visit(UnifiedStringLiteral element, TData data);
		TResult Visit(UnifiedNullLiteral element, TData data);
	}
}