// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Unicoen.WebApps.Metrics.Controllers {
	public partial class MetricsController {
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public MetricsController() { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected MetricsController(Dummy d) { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(ActionResult result) {
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoute(callInfo.RouteValueDictionary);
		}

		[NonAction]
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public System.Web.Mvc.ActionResult Measure() {
			return new T4MVC_ActionResult(Area, Name, ActionNames.Measure);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public MetricsController Actions { get { return MVC.Metrics; } }
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Area = "";
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Name = "Metrics";

		static readonly ActionNamesClass s_actions = new ActionNamesClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionNamesClass ActionNames { get { return s_actions; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNamesClass {
			public readonly string Index = "Index";
			public readonly string Measure = "Measure";
		}


		static readonly ViewNames s_views = new ViewNames();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewNames Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewNames {
            public readonly string Index = "~/Views/Metrics/Index.cshtml";
            public readonly string Measure = "~/Views/Metrics/Measure.cshtml";
		}
	}

	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public class T4MVC_MetricsController: Unicoen.WebApps.Metrics.Controllers.MetricsController {
		public T4MVC_MetricsController() : base(Dummy.Instance) { }

		public override System.Web.Mvc.ActionResult Index() {
			var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
			return callInfo;
		}

		public override System.Web.Mvc.ActionResult Measure(Unicoen.WebApps.Metrics.ViewModels.Metrics.MeasureViewModel model) {
			var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Measure);
			callInfo.RouteValueDictionary.AddOrAddValues("model", model);
			return callInfo;
		}

	}
}

#endregion T4MVC
#pragma warning restore 1591
